# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-present Open Networking Foundation

name: REUSE

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: reuse lint
        run: make reuse-lint
