name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test-pfcpiface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2

      - name: Run unit tests for PFCPSim
        run: |
          make test
