# SPDX-License-Identifier: Apache-2.0
# Copyright 2022-present Open Networking Foundation

name: Unit tests

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-go@v2

      - name: Run unit tests for PFCPSim
        run: |
          make test
